#!/bin/bash
# Tạo Bản đồ Repository (Repo Map) - TEMPLATE
# Cách dùng: bash .agents/scripts/generate_repomap.sh

OUTPUT_FILE="docs/ai/repomap.txt"
mkdir -p docs/ai

echo "Tạo bản đồ mã nguồn tại $OUTPUT_FILE..."

# Ghi Header
echo "# Repo Map" > "$OUTPUT_FILE"
echo "# Auto-generated by .agents/scripts/generate_repomap.sh" >> "$OUTPUT_FILE"
echo "# Last updated: $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Ghi cấu trúc thư mục (level 2)
echo "## Directory Structure" >> "$OUTPUT_FILE"
if command -v tree &> /dev/null; then
    tree -L 2 -I "venv|node_modules|__pycache__|.git" >> "$OUTPUT_FILE"
else
    find . -maxdepth 2 -not -path "*/\.*" -not -name "venv" -not -name "node_modules" | sort >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# TODO: Thêm logic quét các file quan trọng của project bạn vào đây
# Ví dụ cho Node.js/TypeScript:
# grep -rE '^(class|export interface|function)' src/ >> "$OUTPUT_FILE"
# 
# Ví dụ cho Python:
# grep -rE '^(class|def) ' . --include="*.py" >> "$OUTPUT_FILE"

echo "✅ Đã tạo xong $OUTPUT_FILE (Lưu ý: Bạn nên customize script này để quét file tốt hơn)"
